CREATE WAREHOUSE revops_wh
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE revops;
CREATE SCHEMA revops.raw;
CREATE SCHEMA revops.analytics;

SHOW SCHEMAS IN DATABASE revops;